feat: integrate ada handle
teiki-network/teiki-web pull request #2
Opened 2023-02-28 13:29 UTC by sk-tenba

https://app.asana.com/0/1203842063837585/1203857184580238

2023-02-28 13:52 UTC, sk-tenba commented
Since this could not be tested on preview, I could only show the UI after using some mock handle

2023-02-28 13:52 UTC, sk-tenba commented
![Screenshot from 2023-02-28 17-32-57](https://user-images.githubusercontent.com/110231356/221873951-2be21943-0064-4ce4-a453-c485d9f5f119.png)

2023-02-28 13:53 UTC, sk-tenba commented
![Screenshot from 2023-02-28 17-27-39](https://user-images.githubusercontent.com/110231356/221874082-11eed1be-541d-4fd1-ab66-8445772a1699.png)

2023-03-02 08:00 UTC, sk-tenba commented
![Screenshot from 2023-03-02 14-59-38](https://user-images.githubusercontent.com/110231356/222367245-13f40772-490d-4ee1-9f14-aa605e5dc1d0.png)

2023-03-02 09:51 UTC, sk-tenba commented
![Screenshot from 2023-03-02 15-57-24](https://user-images.githubusercontent.com/110231356/222393648-900d36e6-7f6c-4e6b-9f38-ee12309cc5df.png)

2023-03-02 11:55 UTC, sk-tenba commented
![Screenshot from 2023-03-02 18-49-44](https://user-images.githubusercontent.com/110231356/222421706-c3911274-68b2-4c05-bfb0-2b14048f2dca.png)

2023-03-02 11:56 UTC, sk-tenba commented
![Screenshot from 2023-03-02 18-49-35](https://user-images.githubusercontent.com/110231356/222422021-e00732a0-f354-46eb-a00d-b6d1b44a9a74.png)

2023-03-02 11:56 UTC, sk-tenba commented
![Screenshot from 2023-03-02 18-49-27](https://user-images.githubusercontent.com/110231356/222422079-5dfc1ff2-11bc-4fa7-856d-17c2ff7dc450.png)

2023-03-03 03:41 UTC, sk-tenba commented
[Screencast from 03-03-2023 10:40:36.webm](https://user-images.githubusercontent.com/110231356/222625915-509ad6d3-28e8-4e64-89f4-2a4e6158aaa2.webm)

2023-03-03 07:25 UTC, sk-kitsune commented on containers/PageHome/containers/NavBar/containers/ButtonWalletNavbar/containers/ButtonWalletOptions/index.tsx
> +                )}
Change to `Typography.Span`.

The children inside a `Typography.Div` should usually be `<span>`, `Typography.Span`, or anything else with `display: inline` (like `InlineAddress`).

2023-03-03 07:25 UTC, sk-kitsune commented on containers/PageHome/containers/NavBar/containers/ButtonWalletNavbar/containers/ButtonWalletOptions/index.tsx
> +                )}
move `maxLines={1}` to the parent component

2023-03-03 07:28 UTC, sk-kitsune commented on containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionBack.tsx
> +          )}
Actually, `InlineAddress` should handle the logic of ADA handler.

Avoid shotgun surgery.

---

I recommend:

`<InlineAddress value={value.createdBy} length="short" allowAdaHandle={true} />`

2023-03-03 07:28 UTC, sk-kitsune commented on containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionBack.tsx
> +          )}
https://en.wikipedia.org/wiki/Shotgun_surgery

2023-03-03 07:30 UTC, sk-kitsune commented on containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionBack.tsx
> +          )}
change

```
type Props = {
  className?: string;
  style?: React.CSSProperties;
  value: Address;
};
```

to 


```
type Props = {
  className?: string;
  style?: React.CSSProperties;
  value: Address;
  enableAdaHandle?: boolean; // default: true
};
```

2023-03-03 07:32 UTC, sk-kitsune commented on containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionBack.tsx
> +          )}
maybe a required param is a safer choice, i.e. `enableAdaHandle: boolean;`

2023-03-03 07:33 UTC, sk-kitsune commented on modules/common-hooks/hooks/useAdaHandle.ts
> +  const { data, error } = useSWR(address, async (address) => {
The first argument of the useSWR, i.e. the resource key, must be globally unique.

Attach a UUID to make it unique.

---

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-03 07:34 UTC, sk-kitsune commented on modules/common-hooks/hooks/useAdaHandle.ts
> +  const { data, error } = useSWR(address, async (address) => {
If another hook also uses the same key (i.e. `address`) then one hook will see the response of another hook.

2023-03-03 07:35 UTC, sk-kitsune commented on modules/common-hooks/hooks/useAdaHandle.ts
> +    }
`if (!address) return undefined`

2023-03-03 07:37 UTC, sk-kitsune commented on modules/common-hooks/hooks/useAdaHandle.ts
> +    );
https://www.notion.so/shinka-network/RFC-TD-Guidelines-on-using-Server-Side-Props-SSP-48551043ee154ae0bac21ea0625d0cf3?pvs=4#2c0c570e30b841e886ac68f36ba896c8

As a convention, please define `httpGetAdaHandle`.

2023-03-03 07:38 UTC, sk-kitsune commented on modules/common-hooks/hooks/useAdaHandle.ts
> +        const utf8Name = Buffer.from(hexName, "hex").toString("utf8");
where is `Buffer` imported from? are you sure it is available on browser?

2023-03-03 07:39 UTC, sk-kitsune commented on containers/PageProfile/containers/PanelActivities/components/ActivityViewer/components/ActionBack.tsx
> +          )}
🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-03 07:39 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-03 08:50 UTC, sk-shishi commented on config/client.ts
> +export const NEXT_PUBLIC_HANDLE_POLICY_ID: string =
Rename this to `NEXT_PUBLIC_ADA_HANDLE_POLICY_ID`

2023-03-03 08:52 UTC, sk-shishi commented
Please don't merge this. This client-side solution definitely won't scale, as it will send a request to Blockfrost for every address shown on our front-end. It can easily reach the Blockfrost rate limit (per IP).

2023-03-06 03:30 UTC, sk-shishi commented
@sk-kitsune @sk-tenba

I created a new task for the indexing part https://app.asana.com/0/1203842063837585/1204114484985397/f.

To be frank, this PR can be merged (so we can do some UI testing) while waiting for the indexing task to be finished. However, to reduce the number of Blockfrost calls, we need to at least disable all `useSWR` auto-revalidation for that Address->Handle lookup call.

Fyi, Blockfrost rate limit per IP

> We limit an end user, distinguished by IP address, to 10 requests per second. On top of that, we allow each user to send burst of 500 requests, which cools off at rate of 10 requests per second.

2023-03-07 11:14 UTC, sk-shishi commented
@sk-tenba With the upcoming API, we can get the ADA handles of multiple addresses in a single API call. Currently, we're sending one request for each address, which is inefficient. Do you want to handle it now (in this PR) or we'll do it later?

2023-03-07 11:39 UTC, sk-tenba commented
@sk-shishi I think sending multiple addresses would introduce complicated code refactoring. Let's do it later.

2023-03-08 04:56 UTC, closed without merging