feat: v1 project types and refactor
teiki-network/teiki-web pull request #3
Opened 2023-03-01 05:00 UTC by sk-umiuma

This PR updates some of the `business types` version.
Technical decision: https://www.notion.so/shinka-network/RFC-TD-Parsing-business-types-with-version-awareness-23689fa4aed0463dbd79e4963f17a24f

Resolves https://app.asana.com/0/1203842063837585/1204011493163697/f

2023-03-01 10:33 UTC, sk-kitsune commented on containers/PageEditProject/utils.ts
> +export function parseProject(obj: any): Project {
move to `modules/business-types/utils/parsing.ts`

2023-03-01 10:34 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  version: 1;
I don't think we need this.

cc @sk-shishi

2023-03-01 10:35 UTC, sk-kitsune commented on containers/PageEditProject/utils.ts
> +      basics: {
this function is too complex

create `parseProjectBasics`

2023-03-01 10:36 UTC, sk-kitsune commented on containers/PageEditProject/utils.ts
> +  if (!("version" in obj)) {
as discussed the yesterday, we don't need to use `obj.version`

2023-03-01 10:37 UTC, sk-kitsune commented on containers/PageEditProject/utils.ts
> +      basics: {
create `parseProjectImage`, etc

2023-03-01 10:40 UTC, sk-shishi commented on modules/business-types/index.ts
> +  version: 1;
Yeah, not for now (maybe yes in the future), since we're doing "defensive" parsing anyways.

2023-03-01 10:42 UTC, sk-kitsune commented
Avoid [Shotgun Surgery](https://en.wikipedia.org/wiki/Shotgun_surgery).

I understand that a shotgun surgery might be unavoidable. However, we can limit the amount of changes.

This PR is combining 4 changes in one commit. These changes can be split into 4 different PRs.

Reviewing such a big PR is not effective. Merging this PR without effective reviewing is also risky.

2023-03-01 11:42 UTC, sk-shishi commented
> Avoid [Shotgun Surgery](https://en.wikipedia.org/wiki/Shotgun_surgery).
> 
> I understand that a shotgun surgery might be unavoidable. However, we can limit the amount of changes.
> 
> This PR is combining 4 changes in one commit. These changes can be split into 4 different PRs.
> 
> Reviewing such a big PR is not effective. Merging this PR without effective reviewing is also risky.

@sk-kitsune I think we can let it pass for now. When Umiuma switched the strategy to "defensive" parsing midways yesterday, he was already halfway there.

2023-03-03 07:43 UTC, sk-kitsune commented on modules/business-types/utils/parsing.ts
> +    throw new TypeError("invalid boolean");
wrong error message

---

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-03 07:44 UTC, sk-kitsune commented on modules/business-types/utils/parsing.ts
> +function parseJSONContent(obj: any): any {
you should change the return type to JSONContent

2023-03-03 07:59 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  h?: never;
width, height

2023-03-03 08:00 UTC, sk-kitsune commented on modules/business-types/utils/parsing.ts
> +          h: parseNumber(obj?.crop.h),
since `obj` has type `any`, and we don't know what is inside, every field should be accessed with care

```
          x: parseNumber(obj?.crop?.x),
          y: parseNumber(obj?.crop?.y),
          w: parseNumber(obj?.crop?.w),
          h: parseNumber(obj?.crop?.h),
```

2023-03-03 10:05 UTC, sk-kitsune commented on containers/PageUpdateProjectV2/utils/storage.ts
> +  assert(description && basics && roadmapInfo && community, "missing fields");
cannot use assert here, it will be incompatible with the old data.

`const { ... } = parseProject(response.project)`

---

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-03 10:07 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  | { type: "roadmapInfo" }
<img width="325" alt="image" src="https://user-images.githubusercontent.com/117076162/222692585-a4d03a93-919d-4ac1-84a6-d626514cea47.png">

2023-03-03 10:09 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  | { type: "roadmapInfo" }
hmm, it seems that teiki-index does not need to be changed, right?

2023-03-03 10:10 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

---

Please rebase btw.

2023-03-03 10:10 UTC, sk-umiuma commented on modules/business-types/index.ts
> +  | { type: "roadmapInfo" }
I'm aware of this, some stuff do have to change.

2023-03-03 10:16 UTC, sk-kitsune commented on containers/PageUpdateProjectV2/utils/storage.ts
> +  assert(description && basics && roadmapInfo && community, "missing fields");
ignore my comment

2023-03-03 10:17 UTC, sk-kitsune approved these changes
✅ **Approved**: no blocking issues

2023-03-05 14:26 UTC, sk-shishi commented on modules/business-types/index.ts
> +  roadmap: ProjectRoadmapInfo;
@sk-kitsune For this particular case, I'm unsure if we want to rename it to `roadmapInfo`.

1. Those 2 types `{ roadmap: ProjectMilestone[] }` and `{ roadmap: { milestones: ProjectMilestone[] } }` are isomorphic. 
2. The difference between the suggested solution and what Umiuma is doing can be summed up as: `{ fieldOld: TypeA } | { fieldNew: TypeB }` and `{ field: TypeA | TypeB }`. The only difference between them is the "tags" - which we don't really care about in this case - and if we do, we should use the `version` thing instead.
3. Handling the "tagged" version isn't much easier than the "untagged" one in TS / Pg (jsonb). And due to how our queries are written now, they need to be aware of both the old and new types.

So I'm leaning towards using the untagged `{ roadmap: ProjectMilestone[] | { milestones: ProjectMilestones[] } }` and re-evaluating later if we want to add more fields to the `roadmap` type.

On another note, we should share the "parse" logic with `teiki-index` so that the Project Info is already normalized before storing it in the database.

2023-03-05 17:35 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  roadmap: ProjectRoadmapInfo;
@sk-shishi Although I don't have a solid argument, I *feel* that changing a field type is risky.

There is a [reason](https://earthly.dev/blog/backward-and-forward-compatibility/) why protobuf best practices recommend avoid changing a field type, although I understand that protobuf is a different context and we cannot apply protobuf best practices to a TypeScript code base.

If a function calls `obj.roadmap.forEach(...)` (e.g. an old client), I would prefer it to crash because `obj.roadmap` is `undefined`, rather than crash because `obj.roadmap.forEach` is not a function.

What is the drawback of renaming to `roadmapInfo` anyway? If there is no drawback, we can just use it and don't need to worry anything, right?

2023-03-05 17:36 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  roadmap: ProjectRoadmapInfo;
> On another note, we should share the "parse" logic with teiki-index so that the Project Info is already normalized before storing it in the database.

Time to create a new repo namely `teiki-types`?

2023-03-06 03:16 UTC, sk-shishi commented on modules/business-types/index.ts
> +  roadmap: ProjectRoadmapInfo;
@sk-shishi For the particular format (JSON) we're using and how we're handling them (TS, Pg's jsonb), it's perfectly fine to use untagged sum types for these cases, and you also get backward compatibility for free. Of course, only if the types can be easily differentiated from a single check.

> There is a [reason](https://earthly.dev/blog/backward-and-forward-compatibility/) why protobuf best practices recommend avoid changing a field type, although I understand that protobuf is a different context and we cannot apply protobuf best practices to a TypeScript code base.

Because protobuf isn't a self-describing format, it needs to rely on field ordering and field header to determine "how long is this field value in bytes", so an untagged sum type would confuse the deserializer. The same can be said for PlutusTx CBOR and Pg rows. However, JSON is a self-describing, and using an untagged one is idiomatic (see JSON schema `anyof`).

> If a function calls obj.roadmap.forEach(...) (e.g. an old client), I would prefer it to crash because obj.roadmap is undefined, rather than crash because obj.roadmap.forEach is not a function.

To be honest, they are not that different to me... None of them are more ambiguous or more detailed than the other. And in the grand scheme of "old clients", there's more to worry about than just this. Fortunately, this should be rare for us since we only have a single web client, and the cache headers aren't messing things up.

> What is the drawback of renaming to roadmapInfo anyway? If there is no drawback, we can just use it and don't need to worry anything, right?

Well, two reasons:
1. Adding an `info` or `data` suffix is generally not a good idea. They are just noises and don't provide any extra information. `roadmapInfo` is also inconsistent with how we name `community`, `description`,...
2. So that we reach a consensus on how this should be done next time - to reduce review time and collateral change. Because some indexers go through the whole content history, they need to be aware of all the formats (because local testing). @sk-umiuma already needed to change this twice xD.

https://github.com/teiki-network/teiki-index/pull/39
https://github.com/teiki-network/teiki-index/pull/41

2023-03-06 06:26 UTC, sk-kitsune commented on modules/business-types/index.ts
> +  roadmap: ProjectRoadmapInfo;
> They are just noises and don't provide any extra information.


Ok, I agree with this point.

Also, it does not scale if we use `-Info` or `-Data` (`roadmapInfoInfo` is ridiculous). In protobuf, we use number as the field is so this is not an issue.

----

Let me update the TD.

2023-03-07 16:32 UTC, closed without merging