fix: add number of posts
teiki-network/teiki-web pull request #33
Opened 2023-03-07 18:04 UTC by sk-tenba

https://app.asana.com/0/home/1203849283056222/1204124790686694

2023-03-07 18:05 UTC, sk-tenba commented
![image](https://user-images.githubusercontent.com/110231356/223510237-fbf63ab5-8299-4506-94bc-c9e35f0b2d09.png)

2023-03-08 04:46 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.module.scss
> +}
resize the browser --> ui breaks

----

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-08 04:47 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.module.scss
> +}
why using these magic numbers?

2023-03-08 04:48 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.tsx
> +  numOfPosts: number;
The component name is `TabControl`, not `TabControlForPosts`

Do not name your prop `numOfPosts`.

----

🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-08 04:51 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.tsx
> -};
The original code looks clearer.

To show the number, simply add another field `count: number` or `itemCount: number` in the definition of `Tab`.

2023-03-08 05:05 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.tsx
>  }: Props) {
About meaning, you are changing `TabControl` (a dumb component)  to `TabControlInProjectDetails` (a 
smart component).

What are your reasons?

2023-03-08 05:05 UTC, sk-kitsune commented on containers/PageProjectDetails/containers/ProjectDetails/components/TabControl/index.tsx
>  }: Props) {
🔴 **Blocking issue**: this PR cannot be merged until this issue is resolved.

2023-03-08 05:06 UTC, sk-kitsune requested changes
⛔ **Changes requested**: there are blocking issues.

2023-03-08 05:22 UTC, sk-tori commented
@sk-kitsune @sk-tenba This is nice to have, yes, but the Asana task specifically mentions "in platform stats" (on the homepage). This is a completely different thing, solving a "Medium/High" task over a "Highest" task based on how user-facing each is.

2023-03-08 06:37 UTC, sk-tenba commented
Since the amount of code to refactor is quite large, I will resolve this in the upcoming PR

2023-03-08 06:56 UTC, closed without merging